/**
 * Mushaf page asset URLs — task #130, upgraded for #131.
 *
 * The 604 page PNGs of the official Madinah Mushaf are downloaded on
 * first open of the mushaf view, not bundled in the APK. Per user
 * feedback after #130 (the previous release re-uploaded a low-res
 * source), this version pulls from the original high-resolution
 * KFGQPC scans hosted at GovarJabbar/Quran-PNG (2600×4206 px,
 * generated by quran/quran.com-images using KFGQPC fonts) — roughly
 * 2× our earlier source resolution, so the renderer's bilinear
 * downscale has more samples to interpolate from, eliminating the
 * "grainy" stepping the user observed.
 *
 * Served via jsDelivr's GitHub CDN (a publicly-cached, low-latency
 * global mirror) so the user doesn't hit github.com directly. Pages
 * are named `001.png` … `604.png` (3-digit zero-padded).
 *
 * Source repo:    https://github.com/GovarJabbar/Quran-PNG
 * Source license: derived from quran/quran.com-images, which uses
 *                 KFGQPC fonts. Same origin as the official Madinah
 *                 print — no editing applied.
 */

/** Absolute URL of a single mushaf page on the jsDelivr CDN. */
export function mushafPageUrl(page: number): string {
  const safe = Math.max(1, Math.min(604, Math.round(page)));
  const padded = String(safe).padStart(3, '0');
  return `https://cdn.jsdelivr.net/gh/GovarJabbar/Quran-PNG@master/${padded}.png`;
}

/** Total number of pages in the mushaf — matches the standard Madinah print. */
export const MUSHAF_TOTAL_PAGES = 604;

/**
 * Image source spec for `<Image source={…} />`. Returns a `{ uri }`
 * pointing at the GitHub release. RN's image cache will populate
 * itself the first time each page is loaded; we explicitly prefetch
 * all 604 on the user's first download (see `mushafDownload.ts`) so
 * subsequent reads are warm-cache.
 */
export function mushafPageAsset(page: number): { uri: string } {
  return { uri: mushafPageUrl(page) };
}
