/**
 * Mushaf page asset URLs — task #130, refined in #132.
 *
 * The 604 page PNGs of the official KFGQPC Madinah Mushaf are
 * downloaded on first open of the mushaf view, not bundled in the
 * APK. The pages are hosted on THIS repo's own release —
 * `mushaf-assets-v2` on Hassan-PS/PrayerApp — so the app fetches
 * directly from the project we control. No external CDN, no
 * third-party dependency.
 *
 * The asset PNGs are at 2600×4206 px (generated by
 * quran/quran.com-images using KFGQPC fonts, mirrored from
 * GovarJabbar/Quran-PNG). At that resolution the device's bilinear
 * downscale has roughly 2× the source samples our previous
 * 1352×2170 source had, so Arabic text edges no longer step
 * visibly. Pages are named `001.png` … `604.png` (3-digit
 * zero-padded).
 */

/** Absolute URL of a single mushaf page on this repo's release. */
export function mushafPageUrl(page: number): string {
  const safe = Math.max(1, Math.min(604, Math.round(page)));
  const padded = String(safe).padStart(3, '0');
  return `https://github.com/Hassan-PS/PrayerApp/releases/download/mushaf-assets-v2/${padded}.png`;
}

/** Total number of pages in the mushaf — matches the standard Madinah print. */
export const MUSHAF_TOTAL_PAGES = 604;

/**
 * Image source spec for `<Image source={…} />`. Returns a `{ uri }`
 * pointing at the GitHub release. RN's image cache will populate
 * itself the first time each page is loaded; we explicitly prefetch
 * all 604 on the user's first download (see `mushafDownload.ts`) so
 * subsequent reads are warm-cache.
 */
export function mushafPageAsset(page: number): { uri: string } {
  return { uri: mushafPageUrl(page) };
}
