/**
 * Mushaf page layout — the data behind the font-rendered reader (v2.8.0).
 *
 * `data/mushafLayoutV2.json` is generated by `scripts/mushaf/build_qcf_assets.py`
 * from the QPC v2 word data. For every one of the 604 pages it holds the 15
 * printed lines: what kind of line it is, the words on it (as the codepoints
 * of the page's own font, where one glyph is one word), which ayah each word
 * belongs to, and how wide the line is in ems of that font.
 *
 * Two things make the page look like the print rather than like a web page:
 *
 * - **`measure`** — the width of the page's widest line, in ems. The reader
 *   sets `fontSize = availableWidth / measure`, so that line spans the page
 *   exactly and every page ends up the same physical width even though the
 *   fonts are drawn at different design sizes.
 * - **`natural`** — each line's own width in ems. A full line is within ~2% of
 *   the measure, so ordinary word spacing closes the gap invisibly; lines that
 *   close a surah are marked `centered` and are not stretched at all.
 *
 * The raw JSON is kept in its compact on-disk shape and decoded per page on
 * demand — decoding all 604 up front would cost time and memory the reader
 * never needs, since it only ever shows a handful of pages.
 */

type RawSegment = [number, number, number, number] | [number, number, number, number, number];

type RawLine = {
  t: 'a' | 's' | 'b';
  /** Ayah lines: words as font codepoints, separated by "|". */
  x?: string;
  /** Ayah lines: [surah, ayah, firstWordPosition, wordCount, isEnd?] runs. */
  w?: RawSegment[];
  /** Ayah lines: natural width in ems. */
  n?: number;
  /** Ayah lines: each word's advance width, in ems. */
  a?: number[];
  /** Ayah lines: 1 when the line closes a surah and must not be stretched. */
  c?: 1;
  /** Surah/basmalah lines: which surah. */
  s?: number;
};

type RawPage = { p: number; m: number; l: RawLine[] };

export type MushafWord = {
  /** The codepoint(s) to draw with the page font. */
  text: string;
  surah: number;
  ayah: number;
  /** 1-based word position within the ayah (matches the word timing data). */
  position: number;
  /** True for the ayah-number medallion, which QPC treats as a word. */
  isEnd: boolean;
  /**
   * The word's advance width in ems — how far the pen moves, which is NOT
   * how wide the word looks. Several QPC glyphs draw ink far past their
   * advance so they interlock with their neighbours (page 1's basmalah is
   * the clearest). That is why a line is drawn as one text run and taps are
   * resolved against these advances instead of per-word views.
   */
  advance: number;
};

export type MushafLine =
  // Split rather than `kind: 'surah' | 'basmalah'` so the discriminant
  // narrows cleanly at the call sites that switch on it.
  | { kind: 'surah'; surah: number }
  | { kind: 'basmalah'; surah: number }
  | {
      kind: 'ayah';
      words: MushafWord[];
      /** Natural width in ems of the page font. */
      natural: number;
      /** Closes a surah — centred, never stretched. */
      centered: boolean;
    };

export type MushafPageLayout = {
  page: number;
  /** Width of the page's widest line, in ems of the page font. */
  measure: number;
  lines: MushafLine[];
};

/** Lines on a standard page. Pages 1–2 are ornamental plates with fewer. */
export const MUSHAF_LINES_PER_PAGE = 15;

/** Pages 1–2 are framed plates: centred lines, larger text, own proportions. */
export function isFramedPage(page: number): boolean {
  return page === 1 || page === 2;
}

let raw: RawPage[] | null = null;
const decoded = new Map<number, MushafPageLayout>();

function loadRaw(): RawPage[] {
  if (raw == null) {
    // Required lazily: the mushaf reader is one screen of many, and this is
    // the largest data file in the app.
    raw = require('./data/mushafLayoutV2.json') as RawPage[];
  }
  return raw;
}

function decodeLine(line: RawLine): MushafLine | null {
  if (line.t === 's' || line.t === 'b') {
    return {
      kind: line.t === 's' ? 'surah' : 'basmalah',
      surah: line.s ?? 0,
    };
  }
  const tokens = (line.x ?? '').split('|').filter(Boolean);
  const advances = line.a ?? [];
  const words: MushafWord[] = [];
  let i = 0;
  for (const seg of line.w ?? []) {
    const [surah, ayah, first, count, isEnd] = seg;
    for (let k = 0; k < count; k++) {
      const text = tokens[i++];
      if (text == null) break;
      words.push({
        text,
        advance: advances[i - 1] ?? 0,
        surah,
        ayah,
        position: first + k,
        // Only the LAST word of a run flagged `isEnd` is the medallion.
        isEnd: isEnd === 1 && k === count - 1,
      });
    }
  }
  if (words.length === 0) return null;
  return {
    kind: 'ayah',
    words,
    natural: line.n ?? 0,
    centered: line.c === 1,
  };
}

/** Decoded layout for one page, or null when the page is out of range. */
export function getPageLayout(page: number): MushafPageLayout | null {
  const cached = decoded.get(page);
  if (cached) return cached;
  const pages = loadRaw();
  const entry = pages[page - 1];
  if (!entry || entry.p !== page) {
    const found = pages.find(p => p.p === page);
    if (!found) return null;
    return decodePage(found);
  }
  return decodePage(entry);
}

function decodePage(entry: RawPage): MushafPageLayout {
  const cached = decoded.get(entry.p);
  if (cached) return cached;
  const lines = entry.l
    .map(decodeLine)
    .filter((l): l is MushafLine => l != null);
  const layout: MushafPageLayout = {
    page: entry.p,
    measure: entry.m,
    lines,
  };
  decoded.set(entry.p, layout);
  // The reader only ever holds a few pages; keep the decode cache near that.
  if (decoded.size > 24) {
    const oldest = decoded.keys().next().value;
    if (oldest != null && oldest !== entry.p) decoded.delete(oldest);
  }
  return layout;
}

/** Every ayah that appears on a page, in reading order. */
export function ayahsOnPage(page: number): Array<{ surah: number; ayah: number }> {
  const layout = getPageLayout(page);
  if (!layout) return [];
  const out: Array<{ surah: number; ayah: number }> = [];
  for (const line of layout.lines) {
    if (line.kind !== 'ayah') continue;
    for (const w of line.words) {
      const last = out[out.length - 1];
      if (!last || last.surah !== w.surah || last.ayah !== w.ayah) {
        out.push({ surah: w.surah, ayah: w.ayah });
      }
    }
  }
  return out;
}

/** Surahs whose name plate is printed on this page. */
export function surahHeadersOnPage(page: number): number[] {
  const layout = getPageLayout(page);
  if (!layout) return [];
  return layout.lines
    .filter(l => l.kind === 'surah')
    .map(l => (l as { surah: number }).surah);
}

/** Test seam. */
export function _resetLayoutCache(): void {
  decoded.clear();
}
