/**
 * Mushaf page asset URLs — task #130, refined in #132.
 *
 * The 604 page PNGs of the official KFGQPC Madinah Mushaf are
 * downloaded on first open of the mushaf view, not bundled in the
 * APK. The pages are hosted on THIS repo's own release —
 * `mushaf-assets-v2` on Hassan-PS/Mihrab — so the app fetches
 * directly from the project we control. No external CDN, no
 * third-party dependency.
 *
 * The asset PNGs are at 2600×4206 px (generated by
 * quran/quran.com-images using KFGQPC fonts, mirrored from
 * GovarJabbar/Quran-PNG). At that resolution the device's bilinear
 * downscale has roughly 2× the source samples our previous
 * 1352×2170 source had, so Arabic text edges no longer step
 * visibly. Pages are named `001.png` … `604.png` (3-digit
 * zero-padded).
 */

/** Absolute URL of a single mushaf page on this repo's release. */
export function mushafPageUrl(page: number): string {
  const safe = Math.max(1, Math.min(604, Math.round(page)));
  const padded = String(safe).padStart(3, '0');
  return `https://github.com/Hassan-PS/Mihrab/releases/download/mushaf-assets-v2/${padded}.png`;
}

/** Total number of pages in the mushaf — matches the standard Madinah print. */
export const MUSHAF_TOTAL_PAGES = 604;

/**
 * Content crop for pages whose artwork leaves large blank margins —
 * v2.7.28. Fractions of the full 2600×4206 canvas.
 *
 * Pages 1–2 (Al-Fatihah + the opening of Al-Baqarah) are ornamental
 * plates whose content box occupies only ~59% × ~42% of the canvas,
 * pinned to the TOP of the page (measured from the actual PNGs:
 * non-white bbox ≈ x 532–2070, y 165–1921, plus the ayah-marker glyph
 * bounds which extend to y≈1960). Cropping lets the plate render ~60%
 * larger. Pages 3–604 already use ~90% × 95% of the canvas — cropping
 * them would clip the decorative frame for a negligible gain, so they
 * render uncropped.
 */
export type PageCrop = { x: number; y: number; w: number; h: number };

/**
 * Regular pages (3–604) carry a small uniform white margin. The union
 * of the non-white bounding boxes across ALL 602 pages is
 * x 36–2564, y 40–4188 (pixels on the 2600×4206 canvas) — so cropping
 * to that union (with a few px of safety) can never clip content on
 * any page, while buying ~3% larger text on top of the reduced reader
 * padding. Per-page cropping would gain more on average but would make
 * the text size jump between pages while swiping.
 */
const REGULAR_CROP: PageCrop = { x: 0.0115, y: 0.008, w: 0.977, h: 0.9885 };

export function mushafPageCrop(page: number): PageCrop | null {
  if (page === 1 || page === 2) {
    return { x: 0.194, y: 0.033, w: 0.614, h: 0.438 };
  }
  return REGULAR_CROP;
}

/**
 * Image source spec for `<Image source={…} />`.
 *
 * When the managed file store has the page (QR-5), we point at the
 * local `file://` path — fully offline, never evicted. Otherwise we
 * fall back to streaming the page from the GitHub release; the reader
 * stays usable during/after a partial download.
 */
export function mushafPageAsset(
  page: number,
  localPath?: string | null,
): { uri: string } {
  if (localPath) return { uri: `file://${localPath}` };
  return { uri: mushafPageUrl(page) };
}
